// Auto-generated by `supabase gen types` (via the Supabase MCP) against the
// RecruitFlow schema. Regenerate whenever the schema changes:
//   npx supabase gen types typescript --project-id dhanjuydhblrsrdaiezy --schema public > lib/database.types.ts
// Do not edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      activities: {
        Row: {
          actor_id: string | null
          created_at: string
          id: number
          meta: Json
          owner_id: string
          owner_type: Database["public"]["Enums"]["activity_owner_type"]
          verb: string
        }
        Insert: {
          actor_id?: string | null
          created_at?: string
          id?: never
          meta?: Json
          owner_id: string
          owner_type: Database["public"]["Enums"]["activity_owner_type"]
          verb: string
        }
        Update: {
          actor_id?: string | null
          created_at?: string
          id?: never
          meta?: Json
          owner_id?: string
          owner_type?: Database["public"]["Enums"]["activity_owner_type"]
          verb?: string
        }
        Relationships: [
          {
            foreignKeyName: "activities_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      applications: {
        Row: {
          assigned_recruiter_id: string | null
          candidate_id: string
          created_at: string
          employer_id: string | null
          id: string
          job_id: string | null
          source: Database["public"]["Enums"]["record_source"]
          stage: Database["public"]["Enums"]["application_stage"]
          updated_at: string
        }
        Insert: {
          assigned_recruiter_id?: string | null
          candidate_id: string
          created_at?: string
          employer_id?: string | null
          id?: string
          job_id?: string | null
          source?: Database["public"]["Enums"]["record_source"]
          stage?: Database["public"]["Enums"]["application_stage"]
          updated_at?: string
        }
        Update: {
          assigned_recruiter_id?: string | null
          candidate_id?: string
          created_at?: string
          employer_id?: string | null
          id?: string
          job_id?: string | null
          source?: Database["public"]["Enums"]["record_source"]
          stage?: Database["public"]["Enums"]["application_stage"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "applications_assigned_recruiter_id_fkey"
            columns: ["assigned_recruiter_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "applications_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "candidates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "applications_employer_id_fkey"
            columns: ["employer_id"]
            isOneToOne: false
            referencedRelation: "employers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "applications_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_log: {
        Row: {
          action: string
          actor_id: string | null
          created_at: string
          diff: Json | null
          id: number
          ip_address: string | null
          record_id: string | null
          table_name: string | null
        }
        Insert: {
          action: string
          actor_id?: string | null
          created_at?: string
          diff?: Json | null
          id?: never
          ip_address?: string | null
          record_id?: string | null
          table_name?: string | null
        }
        Update: {
          action?: string
          actor_id?: string | null
          created_at?: string
          diff?: Json | null
          id?: never
          ip_address?: string | null
          record_id?: string | null
          table_name?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "audit_log_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      candidate_education: {
        Row: {
          candidate_id: string
          created_at: string
          degree: string | null
          field_of_study: string | null
          graduation_year: string | null
          id: string
          institution: string | null
        }
        Insert: {
          candidate_id: string
          created_at?: string
          degree?: string | null
          field_of_study?: string | null
          graduation_year?: string | null
          id?: string
          institution?: string | null
        }
        Update: {
          candidate_id?: string
          created_at?: string
          degree?: string | null
          field_of_study?: string | null
          graduation_year?: string | null
          id?: string
          institution?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "candidate_education_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "candidates"
            referencedColumns: ["id"]
          },
        ]
      }
      candidate_experience: {
        Row: {
          candidate_id: string
          company: string | null
          created_at: string
          description: string | null
          end_date: string | null
          id: string
          is_current: boolean
          start_date: string | null
          title: string | null
        }
        Insert: {
          candidate_id: string
          company?: string | null
          created_at?: string
          description?: string | null
          end_date?: string | null
          id?: string
          is_current?: boolean
          start_date?: string | null
          title?: string | null
        }
        Update: {
          candidate_id?: string
          company?: string | null
          created_at?: string
          description?: string | null
          end_date?: string | null
          id?: string
          is_current?: boolean
          start_date?: string | null
          title?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "candidate_experience_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "candidates"
            referencedColumns: ["id"]
          },
        ]
      }
      candidate_skills: {
        Row: {
          candidate_id: string
          id: string
          is_primary: boolean
          skill: string
        }
        Insert: {
          candidate_id: string
          id?: string
          is_primary?: boolean
          skill: string
        }
        Update: {
          candidate_id?: string
          id?: string
          is_primary?: boolean
          skill?: string
        }
        Relationships: [
          {
            foreignKeyName: "candidate_skills_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "candidates"
            referencedColumns: ["id"]
          },
        ]
      }
      candidates: {
        Row: {
          assigned_recruiter_id: string | null
          certifications: string | null
          consent_given: boolean
          created_at: string
          current_employer: string | null
          current_title: string | null
          deleted_at: string | null
          email: string | null
          expected_salary: string | null
          field_of_study: string | null
          full_name: string
          graduation_year: string | null
          highest_degree: string | null
          id: string
          linkedin_url: string | null
          location: string | null
          notice_period: string | null
          phone: string | null
          photo_document_id: string | null
          preferred_industry: string | null
          primary_skills: string | null
          search_vector: unknown
          secondary_skills: string | null
          source: Database["public"]["Enums"]["record_source"]
          status: Database["public"]["Enums"]["candidate_status"]
          target_role: string | null
          total_experience: string | null
          university: string | null
          updated_at: string
          work_preference: string | null
        }
        Insert: {
          assigned_recruiter_id?: string | null
          certifications?: string | null
          consent_given?: boolean
          created_at?: string
          current_employer?: string | null
          current_title?: string | null
          deleted_at?: string | null
          email?: string | null
          expected_salary?: string | null
          field_of_study?: string | null
          full_name: string
          graduation_year?: string | null
          highest_degree?: string | null
          id?: string
          linkedin_url?: string | null
          location?: string | null
          notice_period?: string | null
          phone?: string | null
          photo_document_id?: string | null
          preferred_industry?: string | null
          primary_skills?: string | null
          search_vector?: unknown
          secondary_skills?: string | null
          source?: Database["public"]["Enums"]["record_source"]
          status?: Database["public"]["Enums"]["candidate_status"]
          target_role?: string | null
          total_experience?: string | null
          university?: string | null
          updated_at?: string
          work_preference?: string | null
        }
        Update: {
          assigned_recruiter_id?: string | null
          certifications?: string | null
          consent_given?: boolean
          created_at?: string
          current_employer?: string | null
          current_title?: string | null
          deleted_at?: string | null
          email?: string | null
          expected_salary?: string | null
          field_of_study?: string | null
          full_name?: string
          graduation_year?: string | null
          highest_degree?: string | null
          id?: string
          linkedin_url?: string | null
          location?: string | null
          notice_period?: string | null
          phone?: string | null
          photo_document_id?: string | null
          preferred_industry?: string | null
          primary_skills?: string | null
          search_vector?: unknown
          secondary_skills?: string | null
          source?: Database["public"]["Enums"]["record_source"]
          status?: Database["public"]["Enums"]["candidate_status"]
          target_role?: string | null
          total_experience?: string | null
          university?: string | null
          updated_at?: string
          work_preference?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "candidates_assigned_recruiter_id_fkey"
            columns: ["assigned_recruiter_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "candidates_photo_document_id_fkey"
            columns: ["photo_document_id"]
            isOneToOne: false
            referencedRelation: "documents"
            referencedColumns: ["id"]
          },
        ]
      }
      contact_messages: {
        Row: {
          created_at: string
          email: string
          full_name: string
          id: string
          inquiry_type: string | null
          is_handled: boolean
          message: string
          phone: string | null
          subject: string | null
        }
        Insert: {
          created_at?: string
          email: string
          full_name: string
          id?: string
          inquiry_type?: string | null
          is_handled?: boolean
          message: string
          phone?: string | null
          subject?: string | null
        }
        Update: {
          created_at?: string
          email?: string
          full_name?: string
          id?: string
          inquiry_type?: string | null
          is_handled?: boolean
          message?: string
          phone?: string | null
          subject?: string | null
        }
        Relationships: []
      }
      documents: {
        Row: {
          created_at: string
          file_name: string
          id: string
          is_confidential: boolean
          kind: Database["public"]["Enums"]["document_kind"]
          mime_type: string | null
          owner_id: string
          owner_type: Database["public"]["Enums"]["document_owner_type"]
          size_bytes: number | null
          storage_bucket: string
          storage_path: string
          uploaded_by: string | null
        }
        Insert: {
          created_at?: string
          file_name: string
          id?: string
          is_confidential?: boolean
          kind: Database["public"]["Enums"]["document_kind"]
          mime_type?: string | null
          owner_id: string
          owner_type: Database["public"]["Enums"]["document_owner_type"]
          size_bytes?: number | null
          storage_bucket: string
          storage_path: string
          uploaded_by?: string | null
        }
        Update: {
          created_at?: string
          file_name?: string
          id?: string
          is_confidential?: boolean
          kind?: Database["public"]["Enums"]["document_kind"]
          mime_type?: string | null
          owner_id?: string
          owner_type?: Database["public"]["Enums"]["document_owner_type"]
          size_bytes?: number | null
          storage_bucket?: string
          storage_path?: string
          uploaded_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "documents_uploaded_by_fkey"
            columns: ["uploaded_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      employer_contacts: {
        Row: {
          contact_name: string | null
          created_at: string
          designation: string | null
          email: string | null
          employer_id: string
          id: string
          is_primary: boolean
          phone: string | null
        }
        Insert: {
          contact_name?: string | null
          created_at?: string
          designation?: string | null
          email?: string | null
          employer_id: string
          id?: string
          is_primary?: boolean
          phone?: string | null
        }
        Update: {
          contact_name?: string | null
          created_at?: string
          designation?: string | null
          email?: string | null
          employer_id?: string
          id?: string
          is_primary?: boolean
          phone?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "employer_contacts_employer_id_fkey"
            columns: ["employer_id"]
            isOneToOne: false
            referencedRelation: "employers"
            referencedColumns: ["id"]
          },
        ]
      }
      employers: {
        Row: {
          assigned_recruiter_id: string | null
          company_name: string
          company_scale: string | null
          created_at: string
          deleted_at: string | null
          id: string
          industry: string | null
          logo_document_id: string | null
          search_vector: unknown
          source: Database["public"]["Enums"]["record_source"]
          status: Database["public"]["Enums"]["employer_status"]
          updated_at: string
          website_url: string | null
        }
        Insert: {
          assigned_recruiter_id?: string | null
          company_name: string
          company_scale?: string | null
          created_at?: string
          deleted_at?: string | null
          id?: string
          industry?: string | null
          logo_document_id?: string | null
          search_vector?: unknown
          source?: Database["public"]["Enums"]["record_source"]
          status?: Database["public"]["Enums"]["employer_status"]
          updated_at?: string
          website_url?: string | null
        }
        Update: {
          assigned_recruiter_id?: string | null
          company_name?: string
          company_scale?: string | null
          created_at?: string
          deleted_at?: string | null
          id?: string
          industry?: string | null
          logo_document_id?: string | null
          search_vector?: unknown
          source?: Database["public"]["Enums"]["record_source"]
          status?: Database["public"]["Enums"]["employer_status"]
          updated_at?: string
          website_url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "employers_assigned_recruiter_id_fkey"
            columns: ["assigned_recruiter_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "employers_logo_document_id_fkey"
            columns: ["logo_document_id"]
            isOneToOne: false
            referencedRelation: "documents"
            referencedColumns: ["id"]
          },
        ]
      }
      hiring_requests: {
        Row: {
          additional_notes: string | null
          created_at: string
          department: string | null
          employer_id: string | null
          employment_type: string | null
          id: string
          jd_document_id: string | null
          job_description_text: string | null
          job_title: string
          openings_count: string | null
          required_experience: string | null
          required_skills: string | null
          reviewed_by: string | null
          salary_range: string | null
          source: Database["public"]["Enums"]["record_source"]
          status: Database["public"]["Enums"]["hiring_request_status"]
          updated_at: string
          urgency_timeline: string | null
          work_location: string | null
        }
        Insert: {
          additional_notes?: string | null
          created_at?: string
          department?: string | null
          employer_id?: string | null
          employment_type?: string | null
          id?: string
          jd_document_id?: string | null
          job_description_text?: string | null
          job_title: string
          openings_count?: string | null
          required_experience?: string | null
          required_skills?: string | null
          reviewed_by?: string | null
          salary_range?: string | null
          source?: Database["public"]["Enums"]["record_source"]
          status?: Database["public"]["Enums"]["hiring_request_status"]
          updated_at?: string
          urgency_timeline?: string | null
          work_location?: string | null
        }
        Update: {
          additional_notes?: string | null
          created_at?: string
          department?: string | null
          employer_id?: string | null
          employment_type?: string | null
          id?: string
          jd_document_id?: string | null
          job_description_text?: string | null
          job_title?: string
          openings_count?: string | null
          required_experience?: string | null
          required_skills?: string | null
          reviewed_by?: string | null
          salary_range?: string | null
          source?: Database["public"]["Enums"]["record_source"]
          status?: Database["public"]["Enums"]["hiring_request_status"]
          updated_at?: string
          urgency_timeline?: string | null
          work_location?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "hiring_requests_employer_id_fkey"
            columns: ["employer_id"]
            isOneToOne: false
            referencedRelation: "employers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "hiring_requests_jd_document_id_fkey"
            columns: ["jd_document_id"]
            isOneToOne: false
            referencedRelation: "documents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "hiring_requests_reviewed_by_fkey"
            columns: ["reviewed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      jobs: {
        Row: {
          created_at: string
          created_by: string | null
          department: string | null
          description: string | null
          employer_id: string | null
          hiring_request_id: string | null
          id: string
          is_published: boolean
          location: string | null
          published_at: string | null
          requirements: string[]
          salary_display: string | null
          search_vector: unknown
          slug: string
          title: string
          type: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          department?: string | null
          description?: string | null
          employer_id?: string | null
          hiring_request_id?: string | null
          id?: string
          is_published?: boolean
          location?: string | null
          published_at?: string | null
          requirements?: string[]
          salary_display?: string | null
          search_vector?: unknown
          slug: string
          title: string
          type?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          department?: string | null
          description?: string | null
          employer_id?: string | null
          hiring_request_id?: string | null
          id?: string
          is_published?: boolean
          location?: string | null
          published_at?: string | null
          requirements?: string[]
          salary_display?: string | null
          search_vector?: unknown
          slug?: string
          title?: string
          type?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "jobs_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "jobs_employer_id_fkey"
            columns: ["employer_id"]
            isOneToOne: false
            referencedRelation: "employers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "jobs_hiring_request_id_fkey"
            columns: ["hiring_request_id"]
            isOneToOne: false
            referencedRelation: "hiring_requests"
            referencedColumns: ["id"]
          },
        ]
      }
      notes: {
        Row: {
          author_id: string | null
          body: string
          created_at: string
          id: string
          owner_id: string
          owner_type: Database["public"]["Enums"]["note_owner_type"]
          visibility: Database["public"]["Enums"]["note_visibility"]
        }
        Insert: {
          author_id?: string | null
          body: string
          created_at?: string
          id?: string
          owner_id: string
          owner_type: Database["public"]["Enums"]["note_owner_type"]
          visibility?: Database["public"]["Enums"]["note_visibility"]
        }
        Update: {
          author_id?: string | null
          body?: string
          created_at?: string
          id?: string
          owner_id?: string
          owner_type?: Database["public"]["Enums"]["note_owner_type"]
          visibility?: Database["public"]["Enums"]["note_visibility"]
        }
        Relationships: [
          {
            foreignKeyName: "notes_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      permission_grants: {
        Row: {
          area: Database["public"]["Enums"]["permission_area"]
          created_at: string
          granted_by: string | null
          id: string
          user_id: string
        }
        Insert: {
          area: Database["public"]["Enums"]["permission_area"]
          created_at?: string
          granted_by?: string | null
          id?: string
          user_id: string
        }
        Update: {
          area?: Database["public"]["Enums"]["permission_area"]
          created_at?: string
          granted_by?: string | null
          id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "permission_grants_granted_by_fkey"
            columns: ["granted_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "permission_grants_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      placements: {
        Row: {
          application_id: string | null
          candidate_id: string | null
          created_at: string
          created_by: string | null
          employer_id: string | null
          fee_amount: number | null
          guarantee_until: string | null
          id: string
          job_id: string | null
          placed_at: string
          salary_final: string | null
          status: Database["public"]["Enums"]["placement_status"]
          updated_at: string
        }
        Insert: {
          application_id?: string | null
          candidate_id?: string | null
          created_at?: string
          created_by?: string | null
          employer_id?: string | null
          fee_amount?: number | null
          guarantee_until?: string | null
          id?: string
          job_id?: string | null
          placed_at?: string
          salary_final?: string | null
          status?: Database["public"]["Enums"]["placement_status"]
          updated_at?: string
        }
        Update: {
          application_id?: string | null
          candidate_id?: string | null
          created_at?: string
          created_by?: string | null
          employer_id?: string | null
          fee_amount?: number | null
          guarantee_until?: string | null
          id?: string
          job_id?: string | null
          placed_at?: string
          salary_final?: string | null
          status?: Database["public"]["Enums"]["placement_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "placements_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: false
            referencedRelation: "applications"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "placements_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "candidates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "placements_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "placements_employer_id_fkey"
            columns: ["employer_id"]
            isOneToOne: false
            referencedRelation: "employers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "placements_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          email: string | null
          full_name: string
          id: string
          is_active: boolean
          role: Database["public"]["Enums"]["user_role"]
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          email?: string | null
          full_name?: string
          id: string
          is_active?: boolean
          role?: Database["public"]["Enums"]["user_role"]
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          email?: string | null
          full_name?: string
          id?: string
          is_active?: boolean
          role?: Database["public"]["Enums"]["user_role"]
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      can_access_candidate: { Args: { p_id: string }; Returns: boolean }
      can_access_employer: { Args: { p_id: string }; Returns: boolean }
      can_access_owner: {
        Args: { p_id: string; p_type: string }
        Returns: boolean
      }
      current_app_role: {
        Args: never
        Returns: Database["public"]["Enums"]["user_role"]
      }
      has_permission: {
        Args: { p_area: Database["public"]["Enums"]["permission_area"] }
        Returns: boolean
      }
      is_active_user: { Args: never; Returns: boolean }
      is_admin: { Args: never; Returns: boolean }
      is_super_admin: { Args: never; Returns: boolean }
      show_limit: { Args: never; Returns: number }
      show_trgm: { Args: { "": string }; Returns: string[] }
      unaccent: { Args: { "": string }; Returns: string }
    }
    Enums: {
      activity_owner_type:
        | "candidate"
        | "employer"
        | "application"
        | "hiring_request"
        | "job"
      application_stage:
        | "applied"
        | "screening"
        | "submitted_to_client"
        | "interview"
        | "offer"
        | "hired"
        | "rejected"
        | "withdrawn"
      candidate_status:
        | "new"
        | "screening"
        | "shortlisted"
        | "submitted"
        | "interviewing"
        | "offered"
        | "placed"
        | "rejected"
        | "on_hold"
      document_kind:
        | "candidate_photo"
        | "resume"
        | "generated_resume"
        | "employer_logo"
        | "job_description"
        | "certificate"
        | "contract"
        | "other"
      document_owner_type: "candidate" | "employer" | "application"
      employer_status: "prospect" | "active" | "inactive"
      hiring_request_status:
        | "new"
        | "under_review"
        | "approved"
        | "rejected"
        | "published"
      note_owner_type:
        | "candidate"
        | "employer"
        | "application"
        | "hiring_request"
      note_visibility: "team" | "admins_only" | "author_only"
      permission_area:
        | "employer_contacts"
        | "contracts"
        | "fees"
        | "private_notes"
      placement_status: "active" | "guarantee_passed" | "fell_through"
      record_source: "web" | "manual"
      user_role: "super_admin" | "admin" | "recruiter"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      activity_owner_type: [
        "candidate",
        "employer",
        "application",
        "hiring_request",
        "job",
      ],
      application_stage: [
        "applied",
        "screening",
        "submitted_to_client",
        "interview",
        "offer",
        "hired",
        "rejected",
        "withdrawn",
      ],
      candidate_status: [
        "new",
        "screening",
        "shortlisted",
        "submitted",
        "interviewing",
        "offered",
        "placed",
        "rejected",
        "on_hold",
      ],
      document_kind: [
        "candidate_photo",
        "resume",
        "generated_resume",
        "employer_logo",
        "job_description",
        "certificate",
        "contract",
        "other",
      ],
      document_owner_type: ["candidate", "employer", "application"],
      employer_status: ["prospect", "active", "inactive"],
      hiring_request_status: [
        "new",
        "under_review",
        "approved",
        "rejected",
        "published",
      ],
      note_owner_type: [
        "candidate",
        "employer",
        "application",
        "hiring_request",
      ],
      note_visibility: ["team", "admins_only", "author_only"],
      permission_area: [
        "employer_contacts",
        "contracts",
        "fees",
        "private_notes",
      ],
      placement_status: ["active", "guarantee_passed", "fell_through"],
      record_source: ["web", "manual"],
      user_role: ["super_admin", "admin", "recruiter"],
    },
  },
} as const
